spring.application.name=workout-manager

spring.h2.console.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

app.cors.allowed-origins=http://localhost:5173
