CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    name          VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE workouts (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(100) NOT NULL,
    owner_id BIGINT       NOT NULL,
    CONSTRAINT fk_workouts_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE exercises (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    workout_id BIGINT       NOT NULL,
    CONSTRAINT fk_exercises_workout FOREIGN KEY (workout_id) REFERENCES workouts (id) ON DELETE CASCADE
);

CREATE TABLE workout_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performed_at TIMESTAMP(6) NOT NULL,
    workout_id   BIGINT       NOT NULL,
    CONSTRAINT fk_workout_logs_workout FOREIGN KEY (workout_id) REFERENCES workouts (id) ON DELETE CASCADE
);

CREATE TABLE exercise_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weight         DOUBLE PRECISION,
    workout_log_id BIGINT NOT NULL,
    exercise_id    BIGINT NOT NULL,
    CONSTRAINT fk_exercise_logs_workout_log FOREIGN KEY (workout_log_id) REFERENCES workout_logs (id) ON DELETE CASCADE,
    CONSTRAINT fk_exercise_logs_exercise FOREIGN KEY (exercise_id) REFERENCES exercises (id) ON DELETE CASCADE
);

CREATE TABLE measurements (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(50)      NOT NULL,
    measured_value DOUBLE PRECISION NOT NULL,
    measured_at    TIMESTAMP(6)     NOT NULL,
    owner_id       BIGINT           NOT NULL,
    CONSTRAINT fk_measurements_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_workouts_owner_id ON workouts (owner_id);
CREATE INDEX idx_exercises_workout_id ON exercises (workout_id);
CREATE INDEX idx_workout_logs_workout_id ON workout_logs (workout_id);
CREATE INDEX idx_exercise_logs_workout_log_id ON exercise_logs (workout_log_id);
CREATE INDEX idx_exercise_logs_exercise_id ON exercise_logs (exercise_id);
CREATE INDEX idx_measurements_owner_id ON measurements (owner_id);
